<?php
/**
 * Pagination - Show numbered pagination for catalog pages
 *
 * @see 	    https://docs.woocommerce.com/document/template-structure/
 * @author 		WooThemes
 * @package 	WooCommerce/Templates
 * @version     3.3.1
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

global $wp_query;

$total   = isset( $total ) ? $total : wc_get_loop_prop( 'total_pages' );
$current = isset( $current ) ? $current : wc_get_loop_prop( 'current_page' );
$base    = isset( $base ) ? $base : esc_url_raw( str_replace( 999999999, '%#%', remove_query_arg( 'add-to-cart', get_pagenum_link( 999999999, false ) ) ) );
$format  = isset( $format ) ? $format : '';

if ( $total <= 1 ) {
	return;
}

$pagination = lorada_get_opt( 'shop_pagination' );

# fix bug with wrong escaped url generated by next_posts() call
if ( is_search() ) {
	$pagination = 'pagination';
}
?>

<div class="shop-loop-footer">
	<?php 
	if ( 'more-btn' == $pagination || 'infinit' == $pagination ): 
		if ( get_next_posts_link() ) :
			$extra_class = '';

			if ( 'infinit' == $pagination ) { 
				$extra_class = 'load-effect-scroll';
			}
			?>

			<a href="<?php echo next_posts( $wp_query->max_num_pages, false ); ?>" class="lorada-products-load-more lorada-btn <?php echo esc_attr( $extra_class ) ?>">
				<span class="text-label"><?php esc_html_e( 'Load more products', 'lorada' ); ?></span>
				<span class="loading-text-label"><?php esc_html_e( 'Loading...', 'lorada' ); ?></span>
			</a>

			<?php 
		endif; 
	else: 
		?>

		<nav class="lorada-pagination woocommerce-pagination">
			<?php
				echo paginate_links( apply_filters( 'woocommerce_pagination_args', array(
					'base'         => $base,
					'format'       => $format,
					'add_args'     => false,
					'current'      => max( 1, $current ),
					'total'        => $total,
					'prev_text'    => '&larr;',
					'next_text'    => '&rarr;',
					'type'         => 'list',
					'end_size'     => 3,
					'mid_size'     => 3,
				) ) );
			?>
		</nav>

		<?php 
	endif;
	?>
</div>
